package tetris2;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.KeyStroke;

public class GameForm extends javax.swing.JFrame
{
    private GameBoard gb;
    private GameThread gt;
    public GameForm()
    {
        initComponents();
        
        gb = new GameBoard( GamePlaceholder );
        this.add( gb );
        
        initControls();
    }
    
    public void startGame()
    {
        gb.initBackground();
        gt = new GameThread( gb, this );
        gt.start();
    }
    
    private void initControls()
    {
        InputMap im = this.getRootPane().getInputMap();
        ActionMap am = this.getRootPane().getActionMap();
        
        im.put( KeyStroke.getKeyStroke( "RIGHT" ), "right" );
        im.put( KeyStroke.getKeyStroke( "LEFT" ), "left" );
        im.put( KeyStroke.getKeyStroke( "DOWN" ), "down" );
        im.put( KeyStroke.getKeyStroke( "UP" ), "up" );

        am.put( "right", new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                gb.moveTetrominoRight();
                repaint();
            }
        } );
        am.put( "left", new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                gb.moveTetrominoLeft();
                repaint();
            }
        } );
        am.put( "down", new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                gb.dropTetromino();
                repaint();
            }
        } );
        am.put( "up", new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                gb.rotateTetromino();
                repaint();
            }
        } );
    }
    
    public void updateScore( int score )
    {
        scoreLabel.setText("Score: " + score);
    }
    
    public void updateLevel( int level )
    {
        levelLabel.setText("Level: " + level);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        GamePlaceholder = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        pauseButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(230, 230, 230));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        GamePlaceholder.setBackground(new java.awt.Color(250, 250, 250));
        GamePlaceholder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GamePlaceholder.setPreferredSize(new java.awt.Dimension(200, 400));

        javax.swing.GroupLayout GamePlaceholderLayout = new javax.swing.GroupLayout(GamePlaceholder);
        GamePlaceholder.setLayout(GamePlaceholderLayout);
        GamePlaceholderLayout.setHorizontalGroup(
            GamePlaceholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        GamePlaceholderLayout.setVerticalGroup(
            GamePlaceholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        scoreLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        scoreLabel.setText("Score: 0");
        scoreLabel.setMaximumSize(new java.awt.Dimension(120, 30));
        scoreLabel.setMinimumSize(new java.awt.Dimension(70, 30));
        scoreLabel.setPreferredSize(new java.awt.Dimension(120, 30));

        levelLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        levelLabel.setText("Level: 1");
        levelLabel.setMaximumSize(new java.awt.Dimension(100, 30));
        levelLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        levelLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        pauseButton.setText("Pause");
        pauseButton.setPreferredSize(new java.awt.Dimension(70, 30));
        pauseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pauseButtonMouseClicked(evt);
            }
        });
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        menuButton.setText("Main Menu");
        menuButton.setFocusable(false);
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menuButton))
                        .addComponent(GamePlaceholder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(GamePlaceholder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton)
                    .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        
        System.out.print(this.gt.play + " was changed to ");
        this.gt.play = !this.gt.play;
        if( this.gt.play ) pauseButton.setText("Pause");
        if( !this.gt.play ) pauseButton.setText("Play");
        System.out.println(this.gt.play);
        
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void pauseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseButtonMouseClicked

        
    }//GEN-LAST:event_pauseButtonMouseClicked

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed

        gt.interrupt();
        this.setVisible( false );
        Tetris2.showMenu();
        
    }//GEN-LAST:event_menuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GamePlaceholder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton pauseButton;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
